# main.tf

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_container" "web_server" {
  name  = "my_web_server"
  image = "httpd:latest"

  ports {
    internal = 80
    external = 8080
  }

  provisioner "local-exec" {
    command = "echo Web server installed and running on http://localhost:8080"
  }
}
